# ======================================================================================== #
#     ___ _ _   _        _        _      _   _
#    / __(_) |_| |_ _  _| |__    /_\  __| |_(_)___ _ _
#   | (_ | |  _| ' \ || | '_ \  / _ \/ _|  _| / _ \ ' \
#    \___|_|\__|_||_\_,_|_.__/ /_/ \_\__|\__|_\___/_||_|
#
# ======================================================================================== #

name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
